/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ExamplePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var ExamplePlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.registerMarkdownPostProcessor((element, context) => {
      const elements = element.querySelectorAll("a[class='footnote-link']");
      elements.forEach(function(element2) {
        var text = element2.textContent;
        var modifiedText = text.replace(/\[(\d+)-\d+\]/g, "[$1]");
        element2.textContent = modifiedText;
      });
    });
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsibWFpbi50cyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiaW1wb3J0IHsgUGx1Z2luIH0gZnJvbSBcIm9ic2lkaWFuXCI7XG5cbmV4cG9ydCBkZWZhdWx0IGNsYXNzIEV4YW1wbGVQbHVnaW4gZXh0ZW5kcyBQbHVnaW4ge1xuICBhc3luYyBvbmxvYWQoKSB7XG4gICAgdGhpcy5yZWdpc3Rlck1hcmtkb3duUG9zdFByb2Nlc3NvcigoZWxlbWVudCwgY29udGV4dCkgPT4ge1xuICAgICAgY29uc3QgZWxlbWVudHMgPSBlbGVtZW50LnF1ZXJ5U2VsZWN0b3JBbGwoXCJhW2NsYXNzPSdmb290bm90ZS1saW5rJ11cIik7XG4gICAgICBlbGVtZW50cy5mb3JFYWNoKGZ1bmN0aW9uKGVsZW1lbnQpIHtcbiAgICAgICAgdmFyIHRleHQgPSBlbGVtZW50LnRleHRDb250ZW50O1xuICAgICAgICB2YXIgbW9kaWZpZWRUZXh0ID0gdGV4dC5yZXBsYWNlKC9cXFsoXFxkKyktXFxkK1xcXS9nLCAnWyQxXScpO1xuICAgICAgICBlbGVtZW50LnRleHRDb250ZW50ID0gbW9kaWZpZWRUZXh0O1xuICAgICAgfSk7XG4gICAgfSk7XG4gIH1cbn0iXSwKICAibWFwcGluZ3MiOiAiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUEsc0JBQXVCO0FBRXZCLElBQXFCLGdCQUFyQixjQUEyQyx1QkFBTztBQUFBLEVBQ2hELE1BQU0sU0FBUztBQUNiLFNBQUssOEJBQThCLENBQUMsU0FBUyxZQUFZO0FBQ3ZELFlBQU0sV0FBVyxRQUFRLGlCQUFpQiwwQkFBMEI7QUFDcEUsZUFBUyxRQUFRLFNBQVNBLFVBQVM7QUFDakMsWUFBSSxPQUFPQSxTQUFRO0FBQ25CLFlBQUksZUFBZSxLQUFLLFFBQVEsa0JBQWtCLE1BQU07QUFDeEQsUUFBQUEsU0FBUSxjQUFjO0FBQUEsTUFDeEIsQ0FBQztBQUFBLElBQ0gsQ0FBQztBQUFBLEVBQ0g7QUFDRjsiLAogICJuYW1lcyI6IFsiZWxlbWVudCJdCn0K
